{% set version = "1.10.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-styler
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/styler_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/styler/styler_{{ version }}.tar.gz
  sha256: 2c0e33a64fe6e79f463b070f33de297f7ba6531c39332c1e64592bf718e45dfd

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r.cache >=0.14.0
    - r-backports >=1.1.0
    - r-cli >=1.1.0
    - r-magrittr >=2.0.0
    - r-purrr >=0.2.3
    - r-rematch2 >=2.0.1
    - r-rlang >=0.1.1
    - r-rprojroot >=1.1
    - r-tibble >=1.4.2
    - r-withr >=1.0.0
    - r-xfun >=0.1
  run:
    - r-base
    - r-r.cache >=0.14.0
    - r-backports >=1.1.0
    - r-cli >=1.1.0
    - r-magrittr >=2.0.0
    - r-purrr >=0.2.3
    - r-rematch2 >=2.0.1
    - r-rlang >=0.1.1
    - r-rprojroot >=1.1
    - r-tibble >=1.4.2
    - r-withr >=1.0.0
    - r-xfun >=0.1

test:
  commands:
    - $R -e "library('styler')"           # [not win]
    - "\"%R%\" -e \"library('styler')\""  # [win]

about:
  home: https://github.com/r-lib/styler
  license: MIT
  summary: Pretty-prints R code without changing the user's formatting intent.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut

# Package: styler
# Type: Package
# Title: Non-Invasive Pretty Printing of R Code
# Version: 1.1.1
# Authors@R:  c(person(given = "Kirill", family = "Muller", role = "aut", email = "krlmlr+r@mailbox.org"), person(given = "Lorenz", family = "Walthert", role = c("cre", "aut"), email = "lorenz.walthert@icloud.com"))
# Description: Pretty-prints R code without changing the user's formatting intent.
# License: GPL-3
# URL: https://github.com/r-lib/styler
# BugReports: https://github.com/r-lib/styler/issues
# Imports: backports (>= 1.1.0), cli (>= 1.1.0), magrittr (>= 1.0.1), purrr (>= 0.2.3), rematch2 (>= 2.0.1), rlang (>= 0.1.1), rprojroot (>= 1.1), tibble (>= 1.4.2), tools, withr (>= 1.0.0), xfun (>= 0.1)
# Suggests: data.tree (>= 0.1.6), dplyr, here, knitr, prettycode, rmarkdown, rstudioapi (>= 0.7), testthat
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# Collate: 'addins.R' 'communicate.R' 'compat-dplyr.R' 'compat-tidyr.R' 'environments.R' 'expr-is.R' 'indent.R' 'initialize.R' 'io.R' 'nest.R' 'nested-to-tree.R' 'parse.R' 'reindent.R' 'token-define.R' 'relevel.R' 'roxygen-examples-add-remove.R' 'roxygen-examples-find.R' 'roxygen-examples-parse.R' 'roxygen-examples.R' 'rules-line-break.R' 'rules-other.R' 'rules-replacement.R' 'rules-spacing.R' 'serialize.R' 'set-assert-args.R' 'style-guides.R' 'styler.R' 'testing.R' 'token-create.R' 'transform-code.R' 'transform-files.R' 'ui.R' 'unindent.R' 'utils-files.R' 'utils-navigate-nest.R' 'utils-strings.R' 'utils.R' 'vertical.R' 'visit.R' 'zzz.R'
# NeedsCompilation: no
# Packaged: 2019-05-06 20:53:36 UTC; lorenz
# Author: Kirill Muller [aut], Lorenz Walthert [cre, aut]
# Maintainer: Lorenz Walthert <lorenz.walthert@icloud.com>
# Repository: CRAN
# Date/Publication: 2019-05-06 21:50:03 UTC
