{% set version = '1.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-styler
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/styler_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/styler/styler_{{ version }}.tar.gz
  sha256: 05c05ad04f3ce5dfed40da14c6fc6eedc5fa29c0f0262eb70a7f598d50ac44fc

build:
  merge_build_host: True  # [win]
  number: 1000
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-backports
    - r-cli
    - r-magrittr
    - r-purrr >=0.2.3
    - r-rematch2
    - r-rlang
    - r-rprojroot
    - r-tibble >=1.4.2
    - r-withr
    - r-xfun
  run:
    - r-base
    - r-backports
    - r-cli
    - r-magrittr
    - r-purrr >=0.2.3
    - r-rematch2
    - r-rlang
    - r-rprojroot
    - r-tibble >=1.4.2
    - r-withr
    - r-xfun

test:
  commands:
    - $R -e "library('styler')"           # [not win]
    - "\"%R%\" -e \"library('styler')\""  # [win]

about:
  home: https://github.com/r-lib/styler
  license: GPL-3
  summary: Pretty-prints R code without changing the user's formatting intent.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast

# Package: styler
# Title: Non-Invasive Pretty Printing of R Code
# Version: 1.1.0
# Date: 2018-11-20
# Authors@R:  c(person(given = "Kirill", family = "Muller", role = "aut", email = "krlmlr+r@mailbox.org"), person(given = "Lorenz", family = "Walthert", role = c("cre", "aut"), email = "lorenz.walthert@icloud.com"))
# Description: Pretty-prints R code without changing the user's formatting intent.
# License: GPL-3
# URL: https://github.com/r-lib/styler
# BugReports: https://github.com/r-lib/styler/issues
# Imports: backports, cli, magrittr, purrr (>= 0.2.3), rematch2, rlang, rprojroot, tibble (>= 1.4.2), tools, withr, xfun
# Suggests: data.tree, dplyr, here, knitr, prettycode, rmarkdown, rstudioapi, testthat
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# Collate: 'addins.R' 'communicate.R' 'compat-dplyr.R' 'compat-tidyr.R' 'environments.R' 'expr-is.R' 'indent.R' 'initialize.R' 'io.R' 'nest.R' 'nested-to-tree.R' 'parse.R' 'reindent.R' 'token-define.R' 'relevel.R' 'roxygen-examples-add-remove.R' 'roxygen-examples-find.R' 'roxygen-examples-parse.R' 'roxygen-examples.R' 'rules-line-break.R' 'rules-other.R' 'rules-replacement.R' 'rules-spacing.R' 'serialize.R' 'set-assert-args.R' 'style-guides.R' 'styler.R' 'testing.R' 'token-create.R' 'transform-code.R' 'transform-files.R' 'ui.R' 'unindent.R' 'utils.R' 'vertical.R' 'visit.R' 'zzz.R'
# NeedsCompilation: no
# Packaged: 2018-11-20 16:11:24 UTC; lorenz
# Author: Kirill Muller [aut], Lorenz Walthert [cre, aut]
# Maintainer: Lorenz Walthert <lorenz.walthert@icloud.com>
# Repository: CRAN
# Date/Publication: 2018-11-20 16:40:03 UTC
