# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "crcjIo/ngYmWAaGyED9nLr2P2kO45LOlaPEgMLYSBR7Pbu9rXvQRGaYh0l/ZWxOyc16U7v5LnWj9cOFO5Lz4cOxu4UMZjcbtBkq4aTEDQgzWBdyIZXtcuCb6UjStGNh7U3Vi/ChNo84A3fE3MtJP48gE22lXWsWe2mHF+LcMjNzRbZwZKyUYoiUZ7tc9Fs+9p7zxUSXpZFngKeSVbGMZ39R0p+ZcHJbdSigCy6VLEjI70CuStGstp8nsb+MXwrS2o1he21VI9x3EoVQ2208tBMFqgRHqBPqYIdTQUg9fq3/pHrMVTlVrn1rVyRvEL1b3eUzbKmW4KNVGKn5KxVLdpWTpmb/khm1O/+iHEAgjSjsrvOqLE8mQIoPlb2gxeLoqqwaHsiKZqlmXE3UXOoPDmru4M1Ch7kNl2/Kn+XiN1pYRdrFAHgtGtMM4ixdlXq3ZaTYf/qE0ogktuQeo3c3BCI0V7EZ7XnSkfsxpegByOMVecuQpDA9IipYn6PEjNXhhWAcOo7YE8rNLzdbCqDFTJtjxHE16mJdXAYpWYcPseH90Y9FYb5tgy6hrkJHGh5fGbT2mtaFD3FF0L+5bdG3TtDOQuurJXCkvNTehHaycvH0RWbLtbksYZGZfXOpVbADK1xJucUFj18WGZuiNogMoaN3mmtITcieawnE/sEODOQg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
