travis:
  secure:
    BINSTAR_TOKEN: dHpxMkOC7b0NJSpdP3IJG4SHP3uIfEA24TEewuKN8+iQGsW9rhhgI2UEC4rUHRcC+6ME6Cl7AHaTpUxZikcK4YLEZfIbtvYyqS6JNiqkE9Z5uiJ5CIvHBU5kmpnbQkrqi5VTO9tEQa8ngOg1z691vTUlqbccMM7LIjeGBqvC+dw5smjOE7vO4AO+1lExXwAXnHo63ACQi7rkgjr8Ljh3OBql/IZlfOgTtv5aVltpT37mGJ0BQcuSSmBxiDE53NPAMP1grVqXRKHFzbmZnmzvgoLFFz8PjJzvs9xeff2pmKkBukmcacy3PC0D21kLWMNEK1Pl+fK+sn4GZ2xdxzl/s0YKAgIIti3GdZNZJK7PtcvK2cgkpW45KNlMbW6d2aWVNNo3a4KZcZLWPDIphvUFbmUeG75QOwqY5mGHkb3/eb4KmLNsx+Z+D767KPfQOnkxkbDCQPRiQ7l6gEXiJrLr/r0Es8PInd8lpCvYdREeQrvNO3/pTqR6ou5czKA2STDVjzhPRKO5VgrObJUmKriWIv+z3szqtRJvQHCArOKAYXnv1Ax9OVzXJiDLw1yKelkS3Ic4TLsWbKafsewdpOL4BvSQctC2ok/amRTPLV73lWVZsxAZPuKwrkoKdBY/OrMtmesXKL1hhD5elrO5OLK0k6RWkSRo6U160Ni18U8G9p0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
